# -*- coding: utf-8 -*-
"""brAInbuddy_prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAb3290uBw80l0hJxyaPzroQ7x1clZ97
"""

# Import necessary libraries
from IPython.display import display
import ipywidgets as widgets
from textblob import TextBlob

# Function to simulate AI response based on sentiment analysis
def ai_response(user_input):
    sentiment = TextBlob(user_input).sentiment
    if sentiment.polarity > 0:
        return "It sounds like you're feeling pretty good! What made you happy today?"
    elif sentiment.polarity == 0:
        return "I'm here for you. Want to share more about your day?"
    else:
        return "I'm sorry to hear that. It's okay to feel this way. What's on your mind?"

# Function to handle user input
def on_submit(change):
    user_input = change['new']
    response = ai_response(user_input)
    print(f"AI: {response}")
    points_label.value = f"Points: {len(user_input.split()) * 10}"  # Example of gamification: points for words

# Widgets for user input and display
input_box = widgets.Textarea(description="Your Thoughts:")
display(input_box)

input_box.observe(on_submit, names='value')

# Displaying points for gamification
points_label = widgets.Label(value="Points: 0")
display(points_label)

# Static peer support forum simulation
print("\nPeer Support Forum:")
print("- Alex: I've been feeling stressed with exams coming up.")
print("- Sam: I managed to get through my presentation today. Feeling relieved!")
print("- Jamie: Does anyone have tips for dealing with anxiety before a test?")